[project]
name = "yt-trending-mlops-monolith-predict"
version = "1"
dependencies = [
    "pandas",
    "streamlit",
    "boto3",
    "neptune[xgboost]",
    "xgboost",
]

[project.optional-dependencies]
dev = []
